/*
* generated by Xtext
*/
package de.hs_rm.cs.vs.dsm.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FlowAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/hs_rm/cs/vs/dsm/parser/antlr/internal/InternalFlow.tokens");
	}
}
