/*
 * generated by Xtext
 */
package de.hs_rm.cs.vs.dsm.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FlowExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return de.hs_rm.cs.vs.dsm.ui.internal.FlowActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return de.hs_rm.cs.vs.dsm.ui.internal.FlowActivator.getInstance().getInjector("de.hs_rm.cs.vs.dsm.Flow");
	}
	
}
