/*
 * generated by Xtext
 */
package de.hs_rm.cs.vs.dsm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FlowUiModule extends de.hs_rm.cs.vs.dsm.ui.AbstractFlowUiModule {
	public FlowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
