fm = get_instance();
a = fm:create_operator_of_type("a", "CacheIn");
a:set_parameter("list_iris", "http://www.test.de ");
a:set_parameter("connector_socket_address", "localhost");
a:set_parameter("connector_socket_port", "9595");
b = fm:create_operator_of_type("b", "IntAvg");
b:set_parameter("step_size_num", "600000");
b:set_parameter("window_type", "time");
b:set_parameter("element", "element");
fm:connect_operators(b, "out", a, "in");
c = fm:create_operator_of_type("c", "MessageCounter");
c:set_parameter("step_size_num", "30000");
c:set_parameter("window_type", "time");
c:set_parameter("element", "anotherElement");
fm:connect_operators(c, "out", b, "in");
d = fm:create_operator_of_type("d", "StandardDeviation");
d:set_parameter("step_size_num", "7200000");
d:set_parameter("window_type", "time");
d:set_parameter("element", "element");
fm:connect_operators(d, "out", c, "in");
fm:start(d);
fm:start(b);
fm:start(c);
fm:start(a);
fm:stop(d);
fm:stop(b);
fm:stop(c);
fm:stop(a);
