/*
 * generated by Xtext
 */
package de.hs_rm.cs.vs.dsm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FlowRuntimeModule extends de.hs_rm.cs.vs.dsm.AbstractFlowRuntimeModule {

}
